### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dpfaffenbauer** [studioemma/Pimcore-system-migrations-bundle#1]
Could you add some Documentation on how to use your bundle? This actually looks very nice and could become very handy to a lot of people.

**Comment by BlackIkeEagle** [comment]
The documentation will come, first there was a need to get our entire flow working

**Comment by dpfaffenbauer** [comment]
cheers for that, great plugin

**Comment by BlackIkeEagle** [comment]
@dpfaffenbauer thanks
